# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

TOPLEVEL_LANG ?= verilog
# CORE HEADERS
VERILOG_SOURCES += $(shell pwd)/fifo_unit.sv

TOPLEVEL = fifo_unit
MODULE = test_fifo_unit

include $(shell cocotb-config --makefiles)/Makefile.sim